version: '3.7'

services:
  db:
    image: mysql:8.0.17
    container_name: tcp-db
    volumes:
      - 'tcp-mysql:/var/lib/mysql'
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  adminer:
    image: adminer
    ports:
      - 9012:8080

volumes:
  tcp-mysql:
